name: Build and deploy
on: [push]

jobs:
  build:
    name: Build binaries
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: houseabsolute/actions-rust-cross@v0
        with:
          target: aarch64-unknown-linux-gnu
          args: "--locked --release"
          strip: true