name: Build and deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    name: Build and deploy binaries
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup toolchain install stable --profile minimal --no-self-update
      - name: Set up caching
        uses: Swatinem/rust-cache@v2
      - name: Cross compile
        uses: houseabsolute/actions-rust-cross@v0
        with:
          target: aarch64-unknown-linux-gnu
          args: --locked --release
      - name: Connect to Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
      - name: Create github release
        uses: softprops/action-gh-release@v2
        with:
          files: ./target/aarch64-unknown-linux-gnu/release/oliviabot
          tag_name: v0.0.0
      - name: Connect to server and receive binaries
        uses: appleboy/ssh-action@master
        with:
          host: sparrow
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd ${{ secrets.PROJECT_PATH }}
            git pull
            rm -rf target
            mkdir -p target/release
            wget -O target/release/oliviabot https://github.com/RocketRace/oliviabot/releases/latest/download/oliviabot
            chmod +x target/release/oliviabot