name: Build and deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    name: Deploy python source
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - name: Connect to Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
      - name: Connect to server and pull changes
        uses: appleboy/ssh-action@master
        with:
            host: sparrow
            username: ${{ secrets.SSH_USERNAME }}
            password: ${{ secrets.SSH_PASSWORD }}
            script: |
              set -e
              cd ${{ secrets.PROJECT_PATH }}
              git pull --rebase
              ~/.local/bin/poetry env use 3.12
              ~/.local/bin/poetry install --only main
              py=$(~/.local/bin/poetry env info --executable)
              output=$($py scripts/trigger_updates.py)
              if [ $output == bot ]; then
                echo "Restarting bot"
                tmux send -t oliviabot C-c python3 Space bot.py Space prod Enter
              elif [ $output ]; then
                echo "Restarting cogs"
                tmux send -t oliviabot "$output"
              else
                echo "Not restarting anything"
              fi

