name: Build and deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    name: Deploy python source
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - name: Connect to Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
      - name: Connect to server and pull changes
        uses: appleboy/ssh-action@master
        with:
            host: sparrow
            username: ${{ secrets.SSH_USERNAME }}
            password: ${{ secrets.SSH_PASSWORD }}
            script: |
              set -e
              cd ${{ secrets.PROJECT_PATH }}
              touch .updating
              git pull --ff-only
              /bin/env poetry shell
              /bin/env poetry install --only main
              rm .updating