name: Manual restart

on:
  workflow_dispatch

jobs:
  deploy:
    name: Restart
    runs-on: ubuntu-latest
    steps: 
      - name: Connect to Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
      - name: Connect to server and refresh
        uses: appleboy/ssh-action@master
        with:
            host: sparrow
            username: ${{ secrets.SSH_USERNAME }}
            password: ${{ secrets.SSH_PASSWORD }}
            script: |
              set -e
              cd ${{ secrets.PROJECT_PATH }}
              output=$(python scripts/trigger_updates.py)
              if [ $output = bot ]; then
                echo "Restarting bot"
                tmux send -t oliviabot C-c python3 Space bot.py Space prod Enter
              elif [ $output ]; then
                echo "Restarting cogs"
                tmux send -t oliviabot "$output"
              else;
                echo "Not restarting anything"
              fi
